### ISSUE TITLE
i can't search any Chromecast

### ISSUE THREAD

**Issue by battleclem** [ferferga/MMM-GoogleCast#21]
`>>> %Run GetChromecasts.py

Scanning Google Cast devices inside your network...
DEVICE 0
--------------------
Traceback (most recent call last):
  File "/home/pi/MagicMirror/modules/MMM-GoogleCast/GetChromecasts.py", line 8, in <module>
    print("Name: " + cc.device.friendly_name)
AttributeError: 'list' object has no attribute 'device'
>>> `

i restarted my RPi and reinstalled the module and it still can't find my Chrome serise...
same network, just works fine with my phone to cast any music or etc...

**Comment by ferferga** [comment]
This is because this changed in the latest version of pyChromecast. If you checkout the branch 'develop', run the script, finish the configuration steps and checkout 'master' again, you will have this working.

Another solution is to downgrade the pyChromecast version. Of course, as this is present in the develop branch, this will be fixed in the future, when I finish working in the upcoming version.

**Comment by ferferga** [comment]
@battleclem Any news about this?

**Comment by destiny1976** [comment]
I tried your suggestion switching to dev, this results okay, no errors and finding the chromecast(s). After switching to master branch the results: rotating circles on the mirror screen. I assume the module is searching but not finding the chromecast(s)
Any help is welcome, I like the module

**Comment by battleclem** [comment]
​
​
-----Original Message-----

**Comment by sfabrizio** [comment]
I got the same issue.. pivot between develop & master doesn't solve it. What it does solve it is downgrade pyChromecast... to which version? after few tries everything work with pyChromecast v6.0.0 on master branch. 

This will solve it then:
```
sudo pip3 uninstall pychromecast && sudo pip3 install pychromecast==6.0.0
``` 
I recommend to add `sudo pip3 install pychromecast==6.0.0` in the oneline install in the README, so new users like me doesn't encounter this issue anymore.

**Comment by destiny1976** [comment]
> 
> 
> I got the same issue.. pivot between develop & master doesn't solve it. What it does solve it is downgrade pyChromecast... to which version? after few tries everything work with pyChromecast v6.0.0 on master branch.
> 
> This will solve it then:
> 
> ```
> sudo pip3 uninstall pychromecast && sudo pip3 install pychromecast==6.0.0
> ```
> 
> I recommend to add `sudo pip3 install pychromecast==6.0.0` in the oneline install in the README, so new users like me doesn't encounter this issue anymore.

Solved my problem, thank you

**Comment by Electronlibre2012** [comment]
Hello,

same problem like @battleclem , the AttributeError: 'list' object has no attribute 'device',

@ferferga does the module is still maintained please?

It doesnt work with last version 9.1.2, i try 6.0.0, 7.0.1, 8.0.0 without no luck.

Thanks

**Comment by ferferga** [comment]
@Electronlibre2012 I maintain most of my repos, just don't have the same motivation for all of them all the time so sometimes stuff take a while :). 

But I plan an update for this module, just too busy with life right now :)

Can you please try with pyChromecast 4.1.0?

**Comment by Mathias987654321** [comment]
Hello everyone

No idea if that module will be actively supported or if it is "end of life".
Its my first time with magicmirror and so far everything works fine. All modules which I wanted they work.
Now I wanted to install that module, because I am using chromecast's at home.
For me its not possible to to bring that module into the "status" that it works.
If I integrate the module and start my magicmirror.
I can see the module but always a circle is running.
I followed your instruction and when I run your script I get the following error.

raspberry@raspberry:~/MagicMirror $ python3 GetChromecasts.py

Scanning Google Cast devices inside your network...
Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{MDNSServiceInfo(name='JBL-Playlist-45905b729b3c916585b18d634588cadd._googlecast._tcp.local.')})
DEVICE 0

The JBL Playlist (old speaker with had an internal chromecast was / is not a speaker which was activlely in useanymore.
Can't see any other Chromecast's.
As soon I start your script I see all Chromeast devices with ID "python3 GetChromecasts.py" (17 devices)

        {
            module: 'MMM-GoogleCast',
            position: "bottom_right", // Rechts unten
            classes: "default everyone",
            header: "Badezimmer",
            config: {
                device: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            }
        }

I changed the settings / changed devices (with ID from your script) but every time its only loading status inside my magicmirror.

Thanks for your feedback and help

raspberry@raspberry:~/MagicMirror $ pip --version
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
raspberry@raspberry:~/MagicMirror $

**Comment by Mathias987654321** [comment]
I found and resetted / deleted the old JBL Chromecast speaker at home.
First time it didn't wanted to disapear but now it's gone of my google system too.
Now I have no errors during the booting phase in case that the system is not able to connect to my old JBL Speaker.
Now I have the issue the the module is loading and after a while it stop with an unexpected error and say that I have to reboot my magic mirror to solve the issue.
No idea if that helps to solve my problem.
